<a href="https://colab.research.google.com/github/frecklysledge0/CODSOFT/blob/main/Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [78]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [79]:
dataset = pd.read_csv('fraudTrain.csv')
X = dataset.iloc[:, [2,5,12,13,14,15,19,20,21] ].values
y = dataset.iloc[:, -1].values


In [80]:
dataset.isnull().sum()

Unnamed: 0               0
trans_date_trans_time    0
cc_num                   0
merchant                 0
category                 0
amt                      0
first                    0
last                     0
gender                   0
street                   0
city                     0
state                    0
zip                      0
lat                      0
long                     0
city_pop                 0
job                      0
dob                      0
trans_num                0
unix_time                0
merch_lat                0
merch_long               0
is_fraud                 0
dtype: int64

In [81]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)


In [84]:
print(X_train)

[[ 3.59821529e+15  7.16100000e+01  1.17100000e+04 ...  1.35472729e+09
   4.06027630e+01 -7.27872220e+01]
 [ 4.65387924e+15  9.54500000e+01  4.21710000e+04 ...  1.33429774e+09
   3.77352050e+01 -8.68669260e+01]
 [ 3.40951438e+14  8.82000000e+00  1.09620000e+04 ...  1.34135205e+09
   4.02766300e+01 -7.47285680e+01]
 ...
 [ 5.03848303e+11  1.73390000e+02  3.39560000e+04 ...  1.34333100e+09
   2.56857110e+01 -8.13787450e+01]
 [ 3.03602605e+13  1.24900000e+02  6.15600000e+04 ...  1.34396553e+09
   4.20896830e+01 -8.95166040e+01]
 [ 2.29600654e+15  4.08000000e+00  1.12170000e+04 ...  1.33148654e+09
   4.05775660e+01 -7.32222860e+01]]


In [85]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [86]:
print(X_train)

[[-0.31581246  0.00739636 -1.37928766 ...  0.42687548  0.40398941
   1.26646756]
 [-0.31500557  0.15435466 -0.24662645 ... -1.16366196 -0.1571406
   0.24417873]
 [-0.31830214 -0.37966371 -1.40710128 ... -0.61445052  0.34017099
   1.12551174]
 ...
 [-0.31856236  0.63480476 -0.55209284 ... -0.46037992 -2.51501188
   0.64266056]
 [-0.31853954  0.33589502  0.47433374 ... -0.41097913  0.69495316
   0.05179285]
 [-0.3168078  -0.40888277 -1.39761936 ... -1.38252749  0.3990588
   1.23487876]]


In [87]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [88]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [1 0]
 [0 0]
 [0 0]]


In [89]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[256955    950]
 [   748    682]]


0.9934524842385332

In [91]:
dataset1 = pd.read_csv('fraudTest.csv')
X1 = dataset1.iloc[:, [2,5,12,13,14,15,19,20,21] ].values

In [92]:
print(X1)

[[ 2.29116393e+15  2.86000000e+00  2.92090000e+04 ...  1.37181686e+09
   3.39863910e+01 -8.12007140e+01]
 [ 3.57303004e+15  2.98400000e+01  8.40020000e+04 ...  1.37181687e+09
   3.94504980e+01 -1.09960431e+02]
 [ 3.59821529e+15  4.12800000e+01  1.17100000e+04 ...  1.37181689e+09
   4.04958100e+01 -7.41961110e+01]
 ...
 [ 3.00303802e+13  6.67600000e+01  7.86310000e+04 ...  1.38354544e+09
   2.96505050e+01 -9.90820780e+01]
 [ 3.03762380e+13  6.92000000e+00  9.74760000e+04 ...  1.38354547e+09
   4.25647080e+01 -1.24639042e+02]
 [ 2.00000000e+00             nan             nan ...             nan
              nan             nan]]


In [97]:
dataset1.isnull().sum()

Unnamed: 0               0
trans_date_trans_time    0
cc_num                   0
merchant                 1
category                 1
amt                      1
first                    1
last                     1
gender                   1
street                   1
city                     1
state                    1
zip                      1
lat                      1
long                     1
city_pop                 1
job                      1
dob                      1
trans_num                1
unix_time                1
merch_lat                1
merch_long               1
is_fraud                 1
dtype: int64

In [103]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X1 = sc.fit_transform(X1)
X1 = sc.transform(X1)

In [104]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X1[:, 1:9])
X1[:, 1:9] = imputer.transform(X1[:, 1:9])

In [100]:
res=classifier.predict(X1)

In [101]:
print(res)

[0 0 0 ... 0 0 0]
